import Head from 'next/head'
import { useState } from 'react'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Main from '../components/Main'

export default function Home() {
  const [pageNumber,setPageNumber]=useState(1)
  
  return (
    <div className='wallpaper'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <Main  number={pageNumber}/>
      <Footer PG={pageNumber} setPageNumber={setPageNumber}/>
    </div>
  )
}
